name: Dart
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: stable
        flutter-version: '3.0.5'
    - name: Build APK
      run: cd bus_tracking && flutter build apk --release
      
    - name: Copy apk file to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "./bus_tracking/build/app/outputs/flutter-apk/app.apk"
        target: "/home/app.apk"
    
    with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: | 
          cd /home/documentation/data/apk
          rm -rf nwkrtc_tracking.apk
          mv /home/app.apk/bus_tracking/build/app/outputs/flutter-apk/app.apk /home/documentation/data/apk/nwkrtc_tracking.apk
          rm -rf /home/app.apk
