name: Dart
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: stable
        version: 3.05
    - name: Build APK
      run: cd bus_tracking && flutter clean && flutter pub get && flutter build apk --no-fail-on-warning --release
      
    - name: Copy apk file to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "./bus_tracking/build/app/outputs/flutter-apk/app.apk"
        target: "/home/documentation/data/apk/app.apk"
